module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    VENDOR_COLLECTION:'vendor',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ADMIN_COLLECTION:'admin'
}